name: flutter_dialogflow_v2
description: This package is useful to integrate dialogflow v2.1 in your Flutter project, it provides detectIntent request and response data with json mapping.
version: 0.4.1
repository: https://github.com/KalvadTech/flutter_dialogflow
homepage: https://github.com/KalvadTech/flutter_dialogflow
issue_tracker: https://github.com/KalvadTech/flutter_dialogflow/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  googleapis_auth: ^0.2.12+1
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter