name: flutter_dialogflow_v2
description: Flutter package useful to integrate dialogflow v2 only
version: 0.1.0
author: Diego Dal Bosco <diegodalbo97@gmail.com>
repository: https://github.com/diegodalbosco/flutter_dialogflow
homepage: https://diegodalbosco.github.io/flutter_dialogflow/
issue_tracker: https://github.com/diegodalbosco/flutter_dialogflow/issues

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+16
  googleapis_auth: ^0.2.6

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

flutter:

environment:
  sdk: '>=2.1.0 <3.0.0'
